# configuration file for Nginx to proxy requests to the vproapp service(running on port 8080 which is a tomcat server)
upstream vproapp {
 server vproapp:8080;
}
server {
  listen 80;
location / {
  proxy_pass http://vproapp;
}
}