# Docker Compose file for vprofile-project
services:
  # Database service
  vprodb:
    # Build the database image from the specified Dockerfile path 
    build: 
      context: ./Docker-files/db
    # image name for the database service as docker hub accountname/image-name 
    image: kumarsaichandra37/myfirst_devops:db
    # container name from dbimage
    container_name: vprodb
    # Expose port 3306 on the host to port 3306 in the container
    ports:
      - "3306:3306"
    # Define a volume to persist database data
    volumes:
      - vprodbdata:/var/lib/mysql
    # Set environment variables for the database service
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  # memcache service
  vprocache01:
    # Use the official Memcached image from Docker Hub
    image: memcached
    ports:
      - "11211:11211"

  # RabbitMQ service
  vpromq01:
    # Use the official RabbitMQ image from Docker Hub
    image: rabbitmq
    ports:
      - "5672:5672"
    # Set environment variables for RabbitMQ default user and password
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # Application service
  vproapp:
    # build the application image from the specified Dockerfile
    build: 
      context: ./Docker-files/app
    # image name for the application service as docker hub accountname/image-name
    image: kumarsaichandra37/myfirst_devops:app
    # container name from appimage
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    
  # Web server service  
  vproweb:
    # build the web server image from the specified Dockerfile
    build: 
      context: ./Docker-files/web
    # image name for the web server service as docker hub accountname/image-name
    image: kumarsaichandra37/myfirst_devops:web
    # container name from webimage
    container_name: vproweb
    ports:
      - "80:80"

volumes:
   vprodbdata: {}
   vproappdata: {}
  