FROM ubuntu:latest
ENTRYPOINT ["echo"]
CMD ["hello"]           # here default argument is provided for the ENTRYPOINT command, but we can override it during docker run by passing a different argument
